## i.	Download the dataset from above link and load it into your Python environment.

Load dataset

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
df = pd.read_csv('Cellphone.csv')

## ii.	Perform the EDA and do the visualizations.

In [54]:
df.head()

,Product_id,Price,Sale,weight,resoloution,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness
0,203,2357,10,135.0,5.2,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10,110.0,4.7,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11,118.5,4.0,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11,125.0,4.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9

In [55]:
df.drop(columns = ['Product_id'], inplace=True)
df["resolution"] = df["resoloution"].rename("resolution")
df.drop(columns = ["resoloution"],inplace=True)

In [56]:

df.shape
df.head()

,Price,Sale,weight,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness,resolution
0,2357,10,135.0,424,8,1.35,16.0,3.000,13.00,8.0,2610,7.4,5.2
1,1749,10,125.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,4.0
2,1916,10,110.0,312,4,1.20,8.0,1.500,13.00,5.0,2000,7.6,4.7
3,1315,11,118.5,233,2,1.30,4.0,0.512,3.15,0.0,1400,11.0,4.0
4,1749,11,125.0,233,2,1.30,4.0,1.000,3.15,0.0,1700,9.9,4.0

In [57]:
df.isnull().sum()

Price           0
Sale            0
weight          0
ppi             0
cpu core        0
cpu freq        0
internal mem    0
ram             0
RearCam         0
Front_Cam       0
battery         0
thickness       0
resolution      0
dtype: int64

In [58]:
df.describe()

,Price,Sale,weight,ppi,cpu core,cpu freq,internal mem,ram,RearCam,Front_Cam,battery,thickness,resolution
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,2215.596273,621.465839,170.426087,335.055901,4.857143,1.502832,24.501714,2.204994,10.378261,4.503106,2842.111801,8.921739,5.209938
std,768.187171,1546.618517,92.888612,134.826659,2.444016,0.599783,28.804773,1.609831,6.181585,4.342053,1366.990838,2.192564,1.509953
min,614.000000,10.000000,66.000000,121.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,800.000000,5.100000,1.400000
25%,1734.000000,37.000000,134.100000,233.000000,4.000000,1.200000,8.000000,1.000000,5.000000,0.000000,2040.000000,7.600000,4.800000
50%,2258.000000,106.000000,153.000000,294.000000,4.000000,1.400000,16.000000,2.000000,12.000000,5.000000,2800.000000,8.400000,5.150000
75%,2744.000000,382.000000,170.000000,428.000000,8.000000,1.875000,32.000000,3.000000,16.000000,8.000000,3240.000000,9.800000,5.500000
max,4361.000000,9807.000000,753.000000,806.000000,8.000000,2.700000,128.000000,6.000000,23.000000,20.000000,9500.000000,18.500000,12.200000

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Price         161 non-null    int64
 1   Sale          161 non-null    int64
 2   weight        161 non-null    float64
 3   ppi           161 non-null    int64
 4   cpu core      161 non-null    int64
 5   cpu freq      161 non-null    float64
 6   internal mem  161 non-null    float64
 7   ram           161 non-null    float64
 8   RearCam       161 non-null    float64
 9   Front_Cam     161 non-null    float64
 10  battery       161 non-null    int64
 11  thickness     161 non-null    float64
 12  resolution    161 non-null    float64
dtypes: float64(8), int64(5)
memory usage: 16.5 KB

In [60]:
print("Duplicate rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

Duplicate rows: 0

In [61]:
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\2266211817.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [62]:

import matplotlib.pyplot as plt

# 1. RAM vs Price Range
plt.figure(figsize=(8, 5))
plt.scatter(df['ram'], df['Price'], alpha=0.5)
plt.xlabel('RAM')
plt.ylabel('Price Range')
plt.title('RAM vs Price Range')
plt.show()

# 2. Battery Power vs Price Range
plt.figure(figsize=(8, 5))
plt.scatter(df['battery'], df['Price'], alpha=0.5)
plt.xlabel('Battery Power')
plt.ylabel('Price Range')
plt.title('Battery Power vs Price Range')
plt.show()

# 3. Pixel Width vs Price Range
plt.figure(figsize=(8, 5))
plt.scatter(df['ppi'], df['Price'], alpha=0.5)
plt.xlabel('Pixel Width')
plt.ylabel('Price Range')
plt.title('Pixel Width vs Price Range')
plt.show()

#Resolution
# 3. Pixel Width vs Price Range
plt.figure(figsize=(8, 5))
plt.scatter(df['resolution'], df['Price'], alpha=0.5)
plt.xlabel('Resolution')
plt.ylabel('Price Range')
plt.title('Resolution vs Price Range')
plt.show()

C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\2306339102.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\2306339102.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\2306339102.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\2306339102.py:34: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## iii.	Check the distributions/skewness in the variables and do the transformations if required.

In [63]:
sns.histplot(data=df, x='Price', kde=True)
plt.show()

C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3606291948.py:2: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [64]:
df.hist(figsize=(15, 10), bins=20)
plt.tight_layout()
plt.show()

C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\2186199606.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [65]:
numeric_cols = df.select_dtypes(include="number").columns

skewness = df[numeric_cols].skew().sort_values(
    ascending=False
)

print(skewness)

Sale            4.269384
weight          3.981756
internal mem    2.389683
battery         2.092660
thickness       1.587680
resolution      1.176110
Front_Cam       1.169750
ram             0.792698
ppi             0.602503
RearCam         0.106929
Price           0.052347
cpu core       -0.009077
cpu freq       -0.512663
dtype: float64

In [66]:
df['ram'] = np.log1p(df['ram'])
df['thickness'] = np.log1p(df['thickness'])
df['cpu freq'] = np.log1p(df['cpu freq'])
df['battery'] = np.log1p(df['battery'])
df['weight'] = np.log1p(df['weight'])
skewness = df.select_dtypes(include='number').skew()
print(skewness)

Price           0.052347
Sale            4.269384
weight          1.322798
ppi             0.602503
cpu core       -0.009077
cpu freq       -1.649505
internal mem    2.389683
ram            -0.210086
RearCam         0.106929
Front_Cam       1.169750
battery        -0.361261
thickness       0.591625
resolution      1.176110
dtype: float64

## iv.	Check/Treat the outliers and do the feature scaling if required.

In [67]:
df.select_dtypes(include=[np.number]).columns
boxplot_columns = [ 'weight', 'resolution', 'ppi', 'cpu core', 'cpu freq',
       'internal mem', 'ram', 'RearCam', 'Front_Cam', 'battery', 'thickness']
from scipy.stats import boxcox

for column in boxplot_columns:
   sns.boxplot(x=df[column])
   plt.show()

C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\rmehta\AppData\Local\Temp\ipykernel_28760\3005572750.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## iv.	Create a ML model to predict the price of the phone based on the specifications given.

In [68]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

# 1. Separate features and target
X = df.drop(columns='Price')
y = df['Price']

# 2. Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.60, random_state=42
)

#3. Pre processing
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

outliers_cols = ["weight", "resolution", "battery", "internal mem", "thickness", "cpu freq","ppi"]

for col in outliers_cols:
    print(col)
    X_train[col] = df[col].astype(float)
    Q1 = X_train[col].quantile(0.25)
    Q3 = X_train[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outlier_mask = (df[col] < lower_bound) | (X_train[col] > upper_bound)
    median = df[col].median()
    X_train.loc[outlier_mask, col] = median

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

# 4. Create and train the model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# 5. Make predictions
y_pred = model.predict(X_test_scaled)

weight
resolution
battery
internal mem
thickness
cpu freq
ppi

## 6. Evaluate the model, compare training and test result to check overfitting

In [69]:
print("Linear Regression:")
print("Test MAE:", mean_absolute_error(y_test, y_pred))
print("Test MSE:", mean_squared_error(y_test, y_pred))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Test R2 Score:", r2_score(y_test, y_pred))

y_train_pred = model.predict(X_train)
print("Train MAE:", mean_absolute_error(y_train,y_train_pred))
print("Train MSE:", mean_squared_error(y_train, y_train_pred))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, y_train_pred)))
print("Train R2 Score:", r2_score(y_train, y_train_pred))

Linear Regression:
Test MAE: 202.71129515760217
Test MSE: 68619.33218660667
Test RMSE: 261.9529197901918
Test R2 Score: 0.8816953131144663
Train MAE: 83977.49976840876
Train MSE: 9249787626.86815
Train RMSE: 96175.81622668014
Train R2 Score: -15697.266480470962

d:\One Drive\OneDrive - Redi-Direct Marketing Inc\Mgmt\IIT Roorky\Statistics\.venv\Lib\site-packages\sklearn\utils\validation.py:2823: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

## v.	Check for overfitting and use the Regularization techniques if required

In [70]:
model_r = Ridge()
model_r.fit(X_train_scaled,y_train)
y_pred = model_r.predict(X_test_scaled)
print("Ridge Test")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

y_pred = model_r.predict(X_train_scaled)
print("Ridge Train")
print("MAE:", mean_absolute_error(y_train, y_pred))
print("MSE:", mean_squared_error(y_train, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_pred)))
print("R2 Score:", r2_score(y_train, y_pred))

model_l = Lasso()
model_l.fit(X_train_scaled,y_train)
y_pred = model_l.predict(X_test_scaled)
print("Lasso Test")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

y_pred = model_l.predict(X_train_scaled)
print("Lasso Train")
print("MAE:", mean_absolute_error(y_train, y_pred))
print("MSE:", mean_squared_error(y_train, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_pred)))
print("R2 Score:", r2_score(y_train, y_pred))


model_e = ElasticNet()
model_e.fit(X_train,y_train)
y_pred = model_e.predict(X_test_scaled)
print("ElasticNet Test")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

y_pred = model_e.predict(X_train_scaled)
print("ElasticNet Train")
print("MAE:", mean_absolute_error(y_train, y_pred))
print("MSE:", mean_squared_error(y_train, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_pred)))
print("R2 Score:", r2_score(y_train, y_pred))

Ridge Test
MAE: 199.05723827830147
MSE: 66861.60731272677
RMSE: 258.5761151242063
R2 Score: 0.8847257578041606
Ridge Train
MAE: 168.11236715950696
MSE: 48416.974744421146
RMSE: 220.03857558260358
R2 Score: 0.917829186747123
Lasso Test
MAE: 202.23813443912397
MSE: 68580.60242561199
RMSE: 261.8789843145341
R2 Score: 0.8817620860208998
Lasso Train
MAE: 169.42911496468375
MSE: 48257.89917391445
RMSE: 219.67680618106783
R2 Score: 0.9180991616694761
ElasticNet Test
MAE: 1871.3308212305901
MSE: 3865770.19739158
RMSE: 1966.1561986250176
R2 Score: -5.664867147499049
ElasticNet Train
MAE: 1763.8549836017241
MSE: 3485298.868548501
RMSE: 1866.8955162377194
R2 Score: -4.915070984292794

d:\One Drive\OneDrive - Redi-Direct Marketing Inc\Mgmt\IIT Roorky\Statistics\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(
d:\One Drive\OneDrive - Redi-Direct Marketing Inc\Mgmt\IIT Roorky\Statistics\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(

## vi.	Compare the performance metrics of training dataset and testing dataset for all the different algorithms used (Linear/Ridge/Lasso/ElasticNet)

In [71]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet
)
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Separate features and target from the cleaned,
# unscaled DataFrame
X = df.drop(columns="Price")
y = df["Price"]

# Split before fitting preprocessing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

models = {
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=1.0, max_iter=10000),
    "ElasticNet": ElasticNet(
        alpha=1.0,
        l1_ratio=0.5,
        max_iter=10000
    )
}

results = []
fitted_models = {}

for name, estimator in models.items():

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("regressor", estimator)
    ])

    model.fit(X_train, y_train)

    # Separate predictions for training and testing
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Train MAE": mean_absolute_error(
            y_train, train_pred
        ),
        "Test MAE": mean_absolute_error(
            y_test, test_pred
        ),
        "Train RMSE": np.sqrt(
            mean_squared_error(y_train, train_pred)
        ),
        "Test RMSE": np.sqrt(
            mean_squared_error(y_test, test_pred)
        ),
        "Train R2": r2_score(y_train, train_pred),
        "Test R2": r2_score(y_test, test_pred)
    })

    fitted_models[name] = model

results_df = pd.DataFrame(results)
print(results_df.round(3).to_string(index=False))

            Model  Train MAE  Test MAE  Train RMSE  Test RMSE  Train R2  Test R2
Linear Regression    136.383   128.811     169.809    159.674     0.951    0.955
            Ridge    135.639   128.909     170.088    162.285     0.951    0.954
            Lasso    135.770   129.048     170.177    162.594     0.951    0.953
       ElasticNet    152.424   157.284     203.222    227.345     0.930    0.909

## Deployment

In [72]:
import joblib
joblib.dump(model,"Mobile Price Predictor.pk1")

['Mobile Price Predictor.pk1']